version: '3'
services:
    web:
        image: nginx:latest
        container_name: revision-cs-nginx
        entrypoint: ""
        ports:
            - "8000:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./src:/src
        depends_on:
            - php
    php:
        image: php:latest
        container_name: revision-cs-php
        entrypoint: ""
        volumes:
            - ./src:/src
            - ./components:/components
