version: '3'
services:
    web:
        image: nginx:latest
        container_name: cs-nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./src:/src
        depends_on:
            - php
    php:
        image: php:latest
        container_name: cs-php
        volumes:
            - ./src:/src
            - ./components:/components
